apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: registry.example.com/client:latest
        ports:
        - containerPort: 7002
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  selector:
    app: client
  ports:
  - protocol: TCP
    port: 7002
    targetPort: 7002
