apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: registry.example.com/config:latest
        ports:
        - containerPort: 7001
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config
  ports:
  - protocol: TCP
    port: 7001
    targetPort: 7001
